sonar.organization=promise1991
sonar.projectKey=promise1991_git-simulation
sonar.projectName=git-simulation
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**
sonar.sourceEncoding=UTF-8
