name: CD - Deploy
on:
  push:
    branches: [develop, main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 Sonar requires full id instead of v4 tag for security scan to work
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2 Sonar requires full id instead of v4 tag for security scan to work
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-1
      - name: Terraform Deploy Dev
        run: cd infra/envs/dev && terraform init && terraform apply -auto-approve
